modLoader="javafml"
loaderVersion="[1,)"
license="${mod_license}"
showAsResourcePack=false

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="QShop"
description='''A QShop addon that automatically sells items stored in a container.'''

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[21.1.248,)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="qshop"
type="required"
versionRange="[1.2.3,2.0)"
ordering="AFTER"
side="BOTH"
